
export const LOGOUT_USER = 'LOGOUT_USER'
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION'
export const SET_USER = 'SET_USER'
export const GET_USER = 'GET_USER'
export const INVITE_USER = 'INVITE_USER'

export const REPORT_ISSUE = 'REPORT_ISSUE'
export const INVITE_FRIEND = 'INVITE_FRIEND'

export const DATA_LOADED = 'DATA_LOADED'

// SHOWS
export const ADD_SHOW_POPUP = 'ADD_SHOW_POPUP'

export const GET_SHOW_DETAILS = 'GET_SHOW_DETAILS'

export const CREATE_SHOW_REQUEST = 'CREATE_SHOW_REQUEST'
export const CREATE_SHOW_FAILURE = 'CREATE_SHOW_FAILURE'
export const CREATE_SHOW_SUCCESS = 'CREATE_SHOW_SUCCESS'

export const RECEIVE_SHOWS = 'RECEIVE_SHOWS'
export const RECEIVE_SHOWS_ERROR = 'RECEIVE_SHOWS_ERROR'

export const RECEIVE_SHOW_INFO = 'RECEIVE_SHOW_INFO'
export const DELETE_SHOW = 'DELETE_SHOW'

// TOURS
export const CREATE_TOUR_POPUP = 'CREATE_TOUR_POPUP'

export const CREATE_TOUR_REQUEST = 'CREATE_TOUR_REQUEST'
export const CREATE_TOUR_SUCCESS = 'CREATE_TOUR_SUCCESS'
export const CREATE_TOUR_FAILURE = 'CREATE_TOUR_FAILURE'

export const FETCH_TOUR_LIST = 'FETCH_TOUR_LIST'
export const UPDATE_TOUR_LIST = 'UPDATE_TOUR_LIST'
export const FETCH_TOURS_FAILURE = 'FETCH_TOURS_FAILURE'

export const TOUR_DETAILS = 'TOUR_DETAILS'
export const TOUR_CONTROLS = 'TOUR_CONTROLS'
export const TOUR_DELETE = 'TOUR_DELETE'

export const RECEIVE_TOURS = 'RECEIVE_TOURS'
export const RECEIVE_TOURS_ERROR = 'RECEIVE_TOURS_ERROR'

// MERCH
export const ADD_INVENTORY_POPUP = 'ADD_INVENTORY_POPUP'

export const RECEIVE_INVENTORY = 'RECEIVE_INVENTORY'
export const RECEIVE_INVENTORY_ERROR = 'RECEIVE_INVENTORY_ERROR'

export const ADD_INVENTORY_REQUEST = 'ADD_INVENTORY_REQUEST'
export const ADD_INVENTORY_SUCCESS = 'ADD_INVENTORY_SUCCESS'
export const ADD_INVENTORY_FAILURE = 'ADD_INVENTORY_FAILURE'

// BANDS
export const ADD_BAND_POPUP = 'ADD_BAND_POPUP'

export const RECEIVE_BANDS = 'RECEIVE_BANDS'
export const RECEIVE_BANDS_ERROR = 'RECEIVE_BANDS_ERROR'

export const GET_BAND_INFO = 'GET_BAND_INFO'
export const ACTIVE_BAND = 'ACTIVE_BAND'

export const CREATE_BAND_REQUEST = 'CREATE_BAND_REQUEST'
export const CREATE_BAND_SUCCESS = 'CREATE_BAND_SUCCESS'
export const CREATE_BAND_FAILURE = 'CREATE_BAND_FAILURE'

// CONTACTS
export const ADD_CONTACT_POPUP = 'ADD_CONTACT_POPUP'

export const ADD_CONTACT_REQUEST = 'ADD_CONTACT_REQUEST'
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS'
export const ADD_CONTACT_FAILURE = 'ADD_CONTACT_FAILURE'
